title: netique.lol
email: # coming soon
description: >- 
  A digital playground where technology meets creativity. 
  Featuring projects, skills, and some hidden surprises.
baseurl: ""
url: "https://netique.lol"
github_username: 0v3rr1de0

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings
theme: null
accent_color: "#ff1493" # Hot pink

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - memlog
  - README.md
  - LICENSE
  - CNAME
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .git/
  - .gitignore
